# Generated by Django 4.2.2 on 2023-06-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rest_id',
            field=models.TextField(),
        ),
    ]
